GET https://localhost:8443/api/v1/books
Accept: application/json

###

GET https://localhost:8443/api/v1/books/1
Accept: application/json

###

POST https://localhost:8443/api/v1/books
Content-Type: application/json

{
  "name": "XBox 360",
  "author": "Elton",
  "description": "test",
  "status": 1
}

###

PUT https://localhost:8443/api/v1/books/25
Content-Type: application/json

{
"name": "PlayStation 4",
"author": "Elton",
"description": "test",
"status": 1
}

###

DELETE https://localhost:8443/api/v1/books/25

###

POST https://localhost:8443/api/v1/books
Content-Type: application/json

{
  "name": "XBox 360",
  "author": "Elton"
}

###

GET https://localhost:8443/api/v2/books?page=2
Accept: application/json

###

POST https://localhost:8443/api/v2/books
Content-Type: application/json

{
  "name": "XBox 360",
  "author": "Elton",
  "description": "test",
  "status": 1
}

###

DELETE https://localhost:8443/api/v2/books/25

###

GET https://localhost:8443/api/v2/books/search/authors?author=Jon Bentley
Accept: application/json

###

GET https://localhost:8443/api/v2/books/search
Accept: application/json

### 健康检查

GET https://localhost:8443/api/actuator/health
Accept: application/json