spring:
  application:
    name: restful-api
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password:
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /v2
      default-page-size: 10
server:
  servlet:
    context-path: /api
  compression:
    enabled: true
  port: 8443
  #  使用mkcert创建本地证书（https://github.com/FiloSottile/mkcert）
  #  brew install mkcert
  #  mkcert localhost 127.0.0.1 ::1
  #
  # Spring boot 配置HTTP/2 https://byte27.com/2020/02/03/using-http-2-in-your-spring-boot-application/
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:localhost.p12
    key-store-password: 123456
    key-alias: localhost
management:
  endpoint:
    health:
      show-details: always
#
